name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TYPE: ["Debug", "Release"]
        os: [ windows-latest ]
    steps:

    - uses: actions/checkout@v5

    - name: Get MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Show cmake version
      run: cmake --version

    - name: check sf exist
      run: |
        Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Service Fabric\' -Name FabricVersion
      shell: pwsh

    # winmd generate
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 
          8.0.x

    # TODO: newer tool requires dotnet 10.
    - name: install ClangSharpPInvokeGenerator
      run: dotnet tool install --global ClangSharpPInvokeGenerator --version 17.0.1

    - name: restore winmd generator nuget
      run: dotnet restore .metadata\generate.proj

    - name: run cmake
      run: > 
        cmake . -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -B build -T host=x64 -A x64
    - name: clean build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target force_clean

    - name: run generate all
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target generate_winmd

    - name: validate winmd
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target validate_winmd